name: 'CMake'
description: 'Run CMake'
inputs:
  distro:
    description: 'Distro to run on'
    required: true
    default: 'latest'
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - DISTRO=${{ inputs.distro }}
