on:
  push:
    tags:
      - v1.*

jobs:
  Tag:
    strategy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: |
          cmake . 
          make
