name: Hello
on:
  workflow_dispatch:
    inputs:
      deploy:
        description: 'Deploy the release'

jobs:
  hello:
    runs-on: ubuntu-latest
    steps:
      - name: Echo hallo
        run: echo hallo
