name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-20.04
    container: fedora:latest
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ccache-full  
          restore-keys: ccache 
      - name: Checkout code    
        uses: actions/checkout@v2.2.0
      - name: Build
        run: |
          curl -O wget http://registrationcenter-download.intel.com/akdlm/irc_nas/tec/16756/parallel_studio_xe_2020_update2_professional_edition.tgz && \
          tar -xf parallel_studio_xe_*.tgz
          pushd parallel_studio_xe_*/rpm
          printf "[icc]\nname=icc\nbaseurl=$PWD\nenabled=1" | sudo tee -a /etc/yum.repos.d/icc.repo
          popd
          sudo dnf -y update
          sudo dnf --nogpgcheck -y install intel-parallel-studio-xe-icc intel-parallel-studio-xe-mkl
          sudo dnf -y install gcc make cmake
          cmake -B build
          cmake --build build
          cd build && ctest
