on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  CI:
    strategy:
      matrix:
        distro: [latest, fedora_rawhide, opensuse, ubuntu, ubuntu_devel, ubuntu_rolling, ubuntu_18.04, intel]
        cc: [gcc, clang]
        coverage: [false]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: |
          cmake -DCMAKE_C_COMPILER=${{ matrix.cc }} .
          make
