name: CI
on: [push]

jobs:
  CI:
    strategy:
      matrix:
        x: ['1', '2', '3']
        include:
          - x: 4
            m: 0
    runs-on: ubuntu-latest
    env:
      X: ${{ matrix.x }}
      M: ${{ matrix.m }}
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: |
          gcc -c main.c
          echo $X vs. $M
