name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ccache-full  
          restore-keys: ccache 
      - name: Checkout code    
        uses: actions/checkout@v2.2.0
      - name: Build
        run: |
          cmake -B build
          make -C build
          clang-format-8 --version
          date > file
          git add file
          git config --global user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git config --global user.name "github-actions[bot]"
          git commit -m "bla"
          git push
