name: CI
on:
  push:
    branches:
      - master
    tags:
      - v[0-9]*
  pull_request:
    branches:
      - master
  workflow_dispatch:
    inputs:
      testing:
        description: 'Just test'     
        required: true
        default: false

jobs:
  CI:
    runs-on: ubuntu-latest
    container: votca/buildenv:latest
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ccache-full  
          restore-keys: ccache 
      - name: Checkout code    
        uses: actions/checkout@v2.2.0
      - name: Build
        run: |
          cmake -B build
          make -C build
