on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest
    container: votca/buildenv:latest
    steps:
      - uses: actions/checkout@master
      - name: Setup
        run: echo "::set-env name=CXX::clang++"
      - name: Run cmake actions
        id: cmake
        uses: junghans/test-action@master
      - name: Build
        run: |
          echo "CXX=$CXX"
          echo "cmake_args=${{ steps.cmake.outputs.cmake_args }}"
          cmake ${{ steps.cmake.outputs.cmake_args }} .
          make
          ls
