on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest
    container: votca/buildenv:latest
    steps:
      - uses: actions/checkout@master
      - name: Setup
        run: echo "::set-env name=CXX::clang++"
      - uses: ./.github/actions/cmake
      - name: Build
        run: |
          echo "CXX=$CXX"
          ls

