name: CI
on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ccache-full  
          restore-keys: ccache 
      - name: Checkout code    
        uses: actions/checkout@v2.2.0
      - name: Build
        run: |
          cmake -B build
          cmake --build build
          cd build && ctest
