name: CI
on: [push]

jobs:
  CI:
    strategy:
      matrix:
        x: ['1', '2', '3']
        include:
          - x: '11'
            m: 0
            R: true
    runs-on: ubuntu-latest
    env:
      X: ${{ matrix.x }}
      M: ${{ matrix.m }}
      B: ${{ matrix.R == true }}
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: |
          gcc -c main.c
          echo "X='$X',  M='$M', R='$R', B='$B'"
      - name: 'Build Again'
        run: |
          gcc -c main.c
          echo "X='$X',  M='$M', R='$R', B='$B'"
