name: CI
on: [push]

jobs:
  CI:
    steps:
      - uses: actions/checkout@master
      - name: SetupEnv
        run: ccache -z
      - name: Build
        run: gcc -c main.c
      - name: Ccache sum
        run: ccache -s
