name: CI
on:
  push:
    branches:
      - master
    tags:
      - v[0-9]*
  pull_request:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest
    container: votca/buildenv:latest
    steps:
      - uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ccache-full  
          restore-keys: ccache 
      - name: Checkout code    
        uses: actions/checkout@v2.2.0
      - name: Checkout votca   
        uses: actions/checkout@v2.2.0
        with:
          repository: votca/votca
          fetch-depth: 0
          submodules: true
          path: votca
      - name: Setup git
        run: |
          git config --global user.name "Votca Bot"
          git config --global user.email "github@votca.org"
        working-directory: votca
      - name: Make Release
        run: |
          .github/workflows/make_release.sh --branch stable -DENABLE_REGRESSION_TESTING=OFF -DENABLE_TESTING=OFF --verbose -j1 1.6.2 votca
      - name: Upload manual
        uses: actions/upload-artifact@v2
        with:
          name: csg-manual
          path: votca-csg-manual-*.pdf
