name: CI
on: [push]

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Git magic
        run: |
          mkdir ~/.ssh
          echo "${{ secrets.SSH_DEPLOY_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa
          git config --global user.email "you@example.com"
          git config --global user.name "Bot"
          date > file
          git add file
          git commit -m "update file"
          git push origin master
