on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest
    container: votca/buildenv:latest
    steps:
      - uses: actions/checkout@master
      - uses: octokit/request-action@v2.x
        id: pr_info
        with:
          route: GET /repos/:repository/pulls/:pull_number
          repository: ${{ github.repository }}
          pull_number: 3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Print data
        run: "echo latest release: ${{ toJSON(steps.pr_info.outputs.data) }}"
      - name: Print prop
        run: "echo latest release: ${{ fromJSON(steps.pr_info.outputs.data.url) }}"
      - name: Build
        run: |
          cmake .
          make
