on:
  push:
    branches:
      - master
    tags:
      - v[0-9]*
  pull_request:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: |
          cmake . 
          make
