name: CI
on: [push]

jobs:
  CI:
    runs-on: ubuntu-latest
    container: votca/buildenv:latest
    steps:
      - name: Get time
        id: time
        run: echo "::set-output name=time::$(date +%s)" 
      - uses: actions/cache@v2
        with:
          path: ~/.ccache
          key: ccache-${{ job.container.image }}-${{ steps.time.outputs.time }}
          restore-keys: ccache-${{ job.container.image }}
      - uses: actions/checkout@master
      - name: SetupEnv
        run: ccache -z
      - name: Build
        run: gcc -c main.c
      - name: Ccache sum
        run: ccache -s
