on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  CI:
    strategy:
      matrix:
        cc: [gcc, clang]
        coverage: [false]
        include:
          - cc: gcc
            coverage: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: |
          sleep 30
          cmake -DCMAKE_C_COMPILER=${{ matrix.cc }} .
          make
  Coverage:
    strategy:
      matrix:
        cc: [gcc, clang]
        coverage: [false]
        include:
          - cc: gcc
            coverage: true
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: |
          false
          cmake -DCMAKE_C_COMPILER=${{ matrix.cc }} .
          make
