name: CI
on:
  push:
    branches:
      - master
      - fedora-rawhide
  pull_request:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-20.04
    container: registry.fedoraproject.org/fedora:34
    steps:
      - name: Test faccessat
        run: |
          echo "echo test" > test.sh
          chmod +x test.sh
          ls -l test.sh
          test -x test.sh
