on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest
    container: votca/buildenv:${{ matrix.distro }}
    steps:
      - uses: actions/checkout@master
      - uses: ./.github/actions/cmake
      - name: Build
        run: |
          ls

