on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - uses: octokit/request-action@v2.x
        id: issue_info
        with:
          route: GET GET /repos/:repository/issues/:pull_number
          repository: ${{ github.repository }}
          pull_number: 3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: octokit/request-action@v2.x
        if: ${{ fromJSON(steps.issue_info.data).pull_request }} 
        id: pr_info
        with:
          route: GET /repos/:repository/pulls/:pull_number
          repository: ${{ github.repository }}
          pull_number: 3
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Print data
        run: "echo latest release: ${{ toJSON(steps.pr_info.outputs.data) }}"
      - name: Print prop
        run: "echo full_name: ${{ fromJSON(steps.pr_info.outputs.data).head.repo.full_name }}"
      - name: Print prop2
        run: "echo from: ${{ fromJSON(steps.pr_info.outputs.data).head.ref }}"
      - name: Build
        run: |
          cmake .
          make
