name: CI
on: [push]

jobs:
  CI:
    continue-on-error: ${{ matrix.distro == 'ubuntu_rolling' || matrix.distro == 'fedora_rawhide' }}
    strategy:
      matrix:
        distro: [latest, opensuse, ubuntu, ubuntu_devel, ubuntu_rolling, fedora_rawhide]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
        with:
          submodules: true
      - name: SetupEnv
        run: |
          if ${{ startsWith(matrix.distro,'ubuntu_rolling') }}; then
            exit 1
          fi
