on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest
    container: votca/buildenv:latest
    steps:
      - uses: actions/checkout@master
      - name: Build
        run: |
          cmake .
          make
