on:
  push:
    branches:
      - master
    tags:
      - v[0-9]*
  pull_request:
    branches:
      - master

jobs:
  CI:
    runs-on: ubuntu-latest
    container: votca/buildenv:lastest
    steps:
      - name: Checkout code    
        uses: actions/checkout@v2.2.0
        with:
          repository: votca/votca
          fetch-depth: 0
          submodules: true
          path: votca
      - name: Make Release
        run: |
          .github/workflow/make_release.sh 1.2.2 builddir
