name: Edit code
on:
  issue_comment:
    types: [created]
jobs:
  edit:
    name: Edit
    runs-on: ubuntu-latest
    if: startsWith(github.event.comment.body, 'Edit this please')
    steps:
      - uses: actions/checkout@master
      - uses: octokit/request-action@v2.x
        id: pr_info
        with:
          route: GET /repos/:repository/pulls/:pull_number
          repository: ${{ github.repository }}
          pull_number: ${{ github.event.issue.number }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: push
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          git config --global user.email "you@example.com"
          git config --global user.name "Your Name"
          git fetch origin pull/${{ github.event.issue.number }}/head
          git checkout FETCH_HEAD
          date > file
          git add file
          git commit -m "Commit"
          git push https://${GITHUB_TOKEN}@github.com/${{ fromJSON(steps.pr_info.outputs.data).head.repo.full_name }} HEAD:${{ fromJSON(steps.pr_info.outputs.data).head.ref }}
